# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [push]

jobs:
  build-android:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          11    # Minimum supported
        ]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    name: Build APK
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew :android:packageRelease
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: Capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Bubble Blaster Android Build ${{ github.run_number }} (APK)
          path: android/build/outputs/apk/debug
  build-desktop:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17    # Minimum supported
        ]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    name: Build PACKAGE.ZIP
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew :pack
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: Capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Bubble Blaster Desktop Build ${{ github.run_number }} (PACKAGE.ZIP)
          path: desktop-merge/build/dist
