# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build

jobs:
  build:
    on: [ pull_request, push ]
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17    # Minimum supported by Minecraft
        ]
        # and run on both Linux and not Windows
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
        env:
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: capture the game's build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Bubble Blaster
          path: build/libs/
      - name: capture pre-loader's build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Preloader
          path: preloader/build/libs/
  publish:
    on:
      release:
        types: [created]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}