# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [push]

jobs:
  build-linux:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17    # Minimum supported
        ]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} (DEB)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew :desktop-merge:jpackage --info
        env:
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: Capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Bubble Blaster Linux Build ${{ github.run_number }} (DEB)
          path: desktop-merge/build/dist
  build-macos:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17    # Minimum supported
        ]
        os: [macOS-11]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} (APP)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew :desktop-merge:jpackage --info
        env:
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: Capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Bubble Blaster MacOS Build ${{ github.run_number }} (APP)
          path: desktop-merge/build/dist
  build-windows:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17    # Minimum supported
        ]
        os: [windows-2022]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} (EXE)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build
        run: cmd /c "gradlew.bat jpackage --info"
        env:
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: Capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Bubble Blaster Windows Build ${{ github.run_number }} (EXE)
          path: desktop-merge/build/dist
  build-linux-alt:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17    # Minimum supported
        ]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} (PORTABLE)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew :desktop-merge:jpackageAlt --info
        env:
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: Capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Bubble Blaster Linux Build ${{ github.run_number }} (PORTABLE)
          path: desktop-merge/build/dist
  build-macos-alt:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17    # Minimum supported
        ]
        os: [macOS-11]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} (PKG)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew :desktop-merge:jpackageAlt --info
        env:
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: Capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Bubble Blaster MacOS Build ${{ github.run_number }} (PKG)
          path: desktop-merge/build/dist
  build-windows-msi:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17    # Minimum supported
        ]
        os: [windows-2022]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} (MSI)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build
        run: cmd /c "gradlew.bat jpackageAlt --info"
        env:
          GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      - name: Capture the build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Bubble Blaster Windows Build ${{ github.run_number }} (MSI)
          path: desktop-merge/build/dist
